CREATE TABLE workout (
     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email   TEXT NOT NULL ,
    muscle    TEXT NOT NULL  ,
    exercise  TEXT NOT NULL    ,
    sets  INTEGER  ,
    reps    INTEGER  
)